image_width: 1280
image_height: 720
camera_name: arducam_ov9281_usb_camera:_ardu
camera_matrix:
  rows: 3
  cols: 3
  data: [915.44014,   0.     , 656.94362,
           0.     , 928.63513, 305.03559,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.017833, -0.054359, -0.022063, -0.001623, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [920.15015,   0.     , 654.80989,   0.     ,
           0.     , 929.92731, 291.01131,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
